{% set version = "2.95.8" %}

package:
  name: iceoryx-split
  version: {{ version }}

source:
  url: https://github.com/eclipse-iceoryx/iceoryx/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 00b1bf874e17b3e986f11cd134e2be339f3d12643b58b4544692cc4e820439ff
  patches:
    - patches/sha1_cannot_be_empty.diff

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - libacl    # [linux]
    - ncurses  # [unix]

outputs:
  - name: libiceoryx-platform
    files:
      include:
        - lib/libiceoryx_platform*  # [unix]
        - Library/bin/iceoryx_platform*.dll  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]
      host:
        - libacl    # [linux]
        - ncurses  # [unix]
    test:
      commands:
        - test -f ${PREFIX}/lib/libiceoryx_platform${SHLIB_EXT}  # [unix]
        - if not exist "%LIBRARY_BIN%\iceoryx_platform.dll" exit 1  # [win]

  - name: libiceoryx-hoofs
    files:
      include:
        - lib/libiceoryx_hoofs*  # [unix]
        - Library/bin/iceoryx_hoofs*.dll  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]
      host:
        - libacl    # [linux]
        - ncurses  # [unix]
        - {{ pin_subpackage("libiceoryx-platform", exact=True) }}
      run:
        - {{ pin_subpackage("libiceoryx-platform", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libiceoryx_hoofs${SHLIB_EXT}  # [unix]
        - if not exist "%LIBRARY_BIN%\iceoryx_hoofs.dll" exit 1  # [win]

  - name: libiceoryx-posh
    files:
      include:
        - lib/libiceoryx_posh*  # [unix]
        - Library/bin/iceoryx_posh*.dll  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]
      host:
        - libacl    # [linux]
        - ncurses  # [unix]
        - {{ pin_subpackage("libiceoryx-hoofs", exact=True) }}
        - {{ pin_subpackage("libiceoryx-platform", exact=True) }}
      run:
        - {{ pin_subpackage("libiceoryx-hoofs", exact=True) }}
        - {{ pin_subpackage("libiceoryx-platform", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libiceoryx_posh${SHLIB_EXT}  # [unix]
        - if not exist "%LIBRARY_BIN%\iceoryx_posh.dll" exit 1  # [win]

  - name: libiceoryx-binding-c
    files:
      include:
        - lib/libiceoryx_binding_c*  # [unix]
        - Library/bin/iceoryx_binding_c*.dll  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]
      host:
        - libacl    # [linux]
        - ncurses  # [unix]
        - {{ pin_subpackage("libiceoryx-hoofs", exact=True) }}
        - {{ pin_subpackage("libiceoryx-posh", exact=True) }}
      run:
        - {{ pin_subpackage("libiceoryx-hoofs", exact=True) }}
        - {{ pin_subpackage("libiceoryx-posh", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libiceoryx_binding_c${SHLIB_EXT}  # [unix]
        - if not exist "%LIBRARY_BIN%\iceoryx_binding_c.dll" exit 1  # [win]

  - name: libiceoryx-platform-devel
    build:
      run_exports:
        - {{ pin_subpackage("libiceoryx-platform", max_pin="x.x.x") }}
    files:
      include:
        - include/iceoryx/v{{ version }}/iceoryx_versions.hpp  # [unix]
        - include/iceoryx/v{{ version }}/iceoryx_versions.h  # [unix]
        - include/iceoryx/v{{ version }}/iox  # [unix]
        - include/iceoryx/v{{ version }}/iceoryx_platform  # [unix]
        - lib/cmake/iceoryx_platform  # [unix]
        - Library/include/iceoryx/v{{ version }}/iceoryx_versions.hpp  # [win]
        - Library/include/iceoryx/v{{ version }}/iceoryx_versions.h  # [win]
        - Library/include/iceoryx/v{{ version }}/iox  # [win]
        - Library/include/iceoryx/v{{ version }}/iceoryx_platform  # [win]
        - Library/lib/cmake/iceoryx_platform  # [win]
        - Library/lib/iceoryx_platform*.lib  # [win]
    requirements:
      run:
        - {{ pin_subpackage("libiceoryx-platform", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/include/iceoryx/v{{ version }}/iceoryx_versions.hpp  # [unix]
        - test -f ${PREFIX}/include/iceoryx/v{{ version }}/iceoryx_versions.h  # [unix]
        - test -f ${PREFIX}/include/iceoryx/v{{ version }}/iceoryx_platform/inet.hpp  # [unix]
        - if not exist "%LIBRARY_INC%\iceoryx\v{{ version }}\iceoryx_versions.hpp" exit 1  # [win]
        - if not exist "%LIBRARY_INC%\iceoryx\v{{ version }}\iceoryx_versions.h" exit 1  # [win]
        - if not exist "%LIBRARY_INC%\iceoryx\v{{ version }}\iceoryx_platform\inet.hpp" exit 1  # [win]

  - name: libiceoryx-hoofs-devel
    build:
      run_exports:
        - {{ pin_subpackage("libiceoryx-hoofs", max_pin="x.x.x") }}
    files:
      include:
        - include/iceoryx/v{{ version }}/iceoryx_hoofs  # [unix]
        - lib/cmake/iceoryx_hoofs  # [unix]
        - Library/include/iceoryx/v{{ version }}/iceoryx_hoofs  # [win]
        - Library/lib/cmake/iceoryx_hoofs  # [win]
        - Library/lib/iceoryx_hoofs*.lib  # [win]
    requirements:
      run:
        - {{ pin_subpackage("libiceoryx-hoofs", exact=True) }}
        - {{ pin_subpackage("libiceoryx-platform-devel", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/include/iceoryx/v{{ version }}/iceoryx_hoofs/iceoryx_hoofs_types.hpp  # [unix]
        - if not exist "%LIBRARY_INC%\iceoryx\v{{ version }}\iceoryx_hoofs\iceoryx_hoofs_types.hpp" exit 1  # [win]

  - name: libiceoryx-posh-devel
    build:
      run_exports:
        - {{ pin_subpackage("libiceoryx-posh", max_pin="x.x.x") }}
        - {{ pin_subpackage("libiceoryx-hoofs", max_pin="x.x.x") }}
    files:
      include:
        - include/iceoryx/v{{ version }}/iceoryx_posh  # [unix]
        - lib/cmake/iceoryx_posh  # [unix]
        - Library/include/iceoryx/v{{ version }}/iceoryx_posh  # [win]
        - Library/lib/cmake/iceoryx_posh  # [win]
        - Library/lib/iceoryx_posh*.lib  # [win]
    requirements:
      run:
        - {{ pin_subpackage("libiceoryx-hoofs-devel", exact=True) }}
        - {{ pin_subpackage("libiceoryx-posh", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/include/iceoryx/v{{ version }}/iceoryx_posh/version/version_info.hpp  # [unix]
        - if not exist "%LIBRARY_INC%\iceoryx\v{{ version }}\iceoryx_posh\version\version_info.hpp" exit 1  # [win]

  - name: libiceoryx-binding-c-devel
    build:
      run_exports:
        - {{ pin_subpackage("libiceoryx-binding-c", max_pin="x.x.x") }}
    files:
      include:
        - include/iceoryx/v{{ version }}/iceoryx_binding_c  # [unix]
        - lib/cmake/iceoryx_binding  # [unix]
        - Library/include/iceoryx/v{{ version }}/iceoryx_binding_c  # [win]
        - Library/lib/cmake/iceoryx_binding  # [win]
        - Library/lib/iceoryx_binding_c*.lib  # [win]
    requirements:
      run:
        - {{ pin_subpackage("libiceoryx-hoofs-devel", exact=True) }}
        - {{ pin_subpackage("libiceoryx-posh-devel", exact=True) }}
        - {{ pin_subpackage("libiceoryx-binding-c", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/include/iceoryx/v{{ version }}/iceoryx_posh/version/version_info.hpp  # [unix]
        - if not exist "%LIBRARY_INC%\iceoryx\v{{ version }}\iceoryx_posh\version\version_info.hpp" exit 1  # [win]

  - name: iceoryx
    files:
      include:
        - share/doc  # [unix]
        - bin/iox-roudi  # [unix]
        - etc/roudi_config_example.toml  # [unix]
        - Library/share/doc  # [win]
        - Library/bin/iox-roudi.exe  # [win]
        - Library/etc/roudi_config_example.toml  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]
      host:
        - libacl     # [linux]
        - ncurses  # [unix]
        - {{ pin_subpackage("libiceoryx-hoofs", exact=True) }}
        - {{ pin_subpackage("libiceoryx-posh", exact=True) }}
        - {{ pin_subpackage("libiceoryx-binding-c", exact=True) }}
        - {{ pin_subpackage("libiceoryx-hoofs-devel", exact=True) }}
        - {{ pin_subpackage("libiceoryx-posh-devel", exact=True) }}
        - {{ pin_subpackage("libiceoryx-binding-c-devel", exact=True) }}
      run:
        - {{ pin_subpackage("libiceoryx-hoofs", exact=True) }}
        - {{ pin_subpackage("libiceoryx-posh", exact=True) }}
        - {{ pin_subpackage("libiceoryx-binding-c", exact=True) }}
        - {{ pin_subpackage("libiceoryx-hoofs-devel", exact=True) }}
        - {{ pin_subpackage("libiceoryx-posh-devel", exact=True) }}
        - {{ pin_subpackage("libiceoryx-binding-c-devel", exact=True) }}
    test:
      commands:
        - iox-roudi -h

about:
  home: https://iceoryx.io/
  summary: 'Eclipse iceoryx - true zero-copy inter-process-communication'
  description: |
    Eclipse iceoryx is an inter-process-communication middleware that enables
    virtually limitless data transmissions at constant time.
  license: Apache-2.0 AND MIT AND EPL-2.0
  license_file:
    - LICENSE
    - iceoryx_posh/doc/3rd_party_licenses/cpptoml/LICENSE
  doc_url: https://iceoryx.io/latest/
  dev_url: https://github.com/eclipse-iceoryx/iceoryx

extra:
  feedstock-name: iceoryx
  recipe-maintainers:
    - timkpaine
